### ISSUE TITLE
Implementation of Horovod backend in Mesh TensorFlow

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/IDRIS-hackathon#3]
This issue is to track the developments needed to finalize and validate  the Mesh TensorFlow implementation relying on horovod for the backend. This overarching goal will encapsulate several smaller issues. 

### Goal
By the end of the hackweek, submit a Pull Request to https://github.com/tensorflow/mesh with our new implemenation for GPU clusters

### Participants

The main participants to this task are:
  - @tobias-liaudat 
  - @b-remy 

### Tasks

- [x] : Identify reason for deadlocks: DifferentiableUniverseInitiative/mesh#4
- [x] : Fix current implementation bugs: https://github.com/DifferentiableUniverseInitiative/mesh/issues/2
- [ ] : Implement variables: https://github.com/DifferentiableUniverseInitiative/mesh/issues/1
- [ ] : profiling a distributed training task (for instance the demo mnist example)
- [ ] : optimizing

Progress made on these subtasks can be reported here.

**Comment by EiffL** [comment]
And we have identified another issue here, I'm adding it tot the list of things we need to resolve: https://github.com/DifferentiableUniverseInitiative/mesh/issues/4

**Comment by EiffL** [comment]
We have managed to mostly solve this the two first points of this issue, by the following:
- Fixing the random ops in a distributed setting
- Switching to this fork of horovod which doesn't seem to cause any deadlocks  https://github.com/horovod/horovod/pull/2839
