### ISSUE TITLE
Improving support for distributed operations in FlowPM

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/IDRIS-hackathon#5]
This issue is to track the developments needed on FlowPM to make the best of the new Horovod Mesh Implemenation. This overarching goal will encapsulate several smaller issues.

### Goal
By the end of the hackweek, submit a Pull Request to https://github.com/DifferentiableUniverseInitiative/flowpm with tested and benchmarked implementations of N-body and ray-tracing simulations.

### Participants
The main participants to this task are:;
  - @dlanzieri 
  - @santiagocasas

### Tasks
- [ ] : Run benchmarking of a full N-body with and without the Pyramid scheme, and identify the expensive parts https://github.com/DifferentiableUniverseInitiative/flowpm/issues/80 
- [ ] : Implement raytracing operations in Mesh TensorFlow to generate large-scale mass-maps https://github.com/DifferentiableUniverseInitiative/flowpm/issues/81
- [ ] : Test the scaling of the simulation
